
# jetson nano
[data.instance.packages.ubuntu-tegra.desktop]
apt = [
  "direnv",
  "htop",
  "jq",
  "mosh",
  "neovim",
  "shellcheck",
  "zsh"
]
cargo = [
  "--locked bat",
  "--locked zoxide",
  "du-dust",
  "eza",
  "fd-find",
  "jless",
  "ripgrep"
]
ppa = [
  "ppa:neovim-ppa/stable"
]
snap-classic = [ 
  "aws-cli"
]


[data.instance.packages.config.mamba]
environments = [ ]
template_dir = "${XDG_DATA_HOME}/chezmoi/resources/templates/mamba"


[data.instance.packages.config.sdkman]
java_distros = [ ]
