[data.instance.packages.darwin.desktop]
brew = [
  "age",
  "awscli",
  "bat",
  "bitwarden-cli",
  "btop",
  "chezmoi",
  "direnv",
  "dockutil",
  "duckdb",
  "dust",
  "eza",
  "fd",
  "fzf",
  "gnu-units",
  "jless",
  "jq",
  "libpq",
  "mas",
  "micromamba",
  "mosh",
  "nushell",
  "neovim",
  "oh-my-posh",
  "ripgrep",
  "shellcheck",
  "starship",
  "xsv",
  "xz",
  "zoxide",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-fast-syntax-highlighting"
]
cask = [
  "font-jetbrains-mono-nerd-font",
  "font-meslo-lg-nerd-font"
]


[data.instance.packages.darwin.desktop-slim]
brew = [
  "age",
  "bat",
  "btop",
  "chezmoi",
  "direnv",
  "dockutil",
  'dust',
  "eza",
  "fzf",
  "jless",
  "micromamba",
  "neovim",
  "oh-my-posh",
  "ripgrep",
  "zoxide",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-fast-syntax-highlighting"
]
cask = [
  "appcleaner",
  "font-fira-code-nerd-font",
  "font-jetbrains-mono-nerd-font",
  "font-meslo-lg-nerd-font",
  "ghostty",
  "iTerm2",
  "visual-studio-code"
]


[data.instance.packages.config.mamba]
environments = [
  "clx"
]
template_dir = "${XDG_DATA_HOME}/chezmoi/resources/templates/mamba"


[data.instance.packages.config.sdkman]
java_distros = [
  "Corretto"
]
