[data.instance.packages.darwin.desktop]
brew = [
  "age",
  "ascii",
  "awscli",
  "bat",
  "btop",
  "chezmoi",
  "duckdb",
  "dust",
  "eza",
  "fd",
  "fzf",
  "git-delta",
  "gnu-units",
  "jless",
  "jq",
  "libpq",
  "mas",
  "mise",
  "mosh",
  "neovim",
  "octave",
  "oh-my-posh",
  "ripgrep",
  "uv",
  "wget",
  "xsv",
  "xz",
  "zoxide",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-fast-syntax-highlighting"
]
cask = [
  "codex",
  "font-jetbrains-mono-nerd-font",
  "font-meslo-lg-nerd-font",
  "font-stardos-stencil"
]


[data.instance.packages.darwin.ephemeral]
brew = [
  "age",
  "bat",
  "btop",
  "chezmoi",
  "cmake",
  "dust",
  "eza",
  "fd",
  "fzf",
  "git-delta",
  "jless",
  "mise",
  "neovim",
  "oh-my-posh",
  "protobuf",
  "ripgrep",
  "uv",
  "wget",
  "zoxide",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-fast-syntax-highlighting"
]
cask = [
  "appcleaner",
  "codex",
  "font-charis",
  "font-gentium",
  "font-jetbrains-mono-nerd-font",
  "font-meslo-lg-nerd-font",
  "ghostty",
  "iTerm2",
  "obsidian",
  "visual-studio-code",
  "vivaldi"
]


[data.instance.packages.config.mamba]
environments = [ ]
template_dir = "${XDG_DATA_HOME}/chezmoi/resources/mamba"


[data.instance.packages.config.sdkman]
java_distros = [ ]
