# raspberry pi
[data.instance.packages.debian-rpi.desktop]
apt = [
  "bat",
  "btop",
  "fd-find",
  "i2c-tools",
  "libxcb-render0-dev",
  "libxcb-shape0-dev",
  "libxcb-xfixes0-dev",
  "locales-all",
  "mosh",
  "python3-smbus",
  "ripgrep",
  "shellcheck",
  "speedtest-cli",
  "zsh"
]
cargo = [
  "--locked bat",
  "--locked zoxide",
  "du-dust",
  "eza",
  "jless"
]
