
# jetson nano
[data.instance.packages.ubuntu-tegra.desktop]
apt = [
  "htop",
  "jq",
  "mosh",
  "neovim",
  "shellcheck",
  "zsh"
]
cargo = [
  "--locked bat",
  "--locked zoxide",
  "du-dust",
  "eza",
  "fd-find",
  "jless",
  "ripgrep"
]
ppa = [
  "ppa:neovim-ppa/stable"
]
snap-classic = [ 
  "aws-cli"
]
