[data.instance.packages.ubuntu.server]
apt = [
  "bat",
  "btop",
  "du-dust",
  "eza",
  "fd-find",
  "fzf",
  "ripgrep",
  "shellcheck",
  "unzip",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
snap = [ ]
snap-classic = [
  "aws-cli" 
]


[data.instance.packages.ubuntu.desktop]
apt = [
  "bat",
  "btop",
  "du-dust",
  "eza",
  "fd-find",
  "fzf",
  "ripgrep",
  "shellcheck",
  "unzip",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
snap = [
  "vivaldi"
]
