[data.instance.packages.ubuntu.server]
apt = [
  "bat",
  "btop",
  "du-dust",
  "eza",
  "fd-find",
  "fzf",
  "ripgrep",
  "shellcheck",
  "unzip",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
snap = [ ]
snap-classic = [
  "aws-cli" 
]


[data.instance.packages.ubuntu.desktop]
apt = [
  "bat",
  "btop",
  "du-dust",
  "eza",
  "fd-find",
  "fzf",
  "ripgrep",
  "shellcheck",
  "unzip",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
snap = [
  "vivaldi"
]
snap-classic = [
  "aws-cli"
]


[data.instance.packages.config.mamba]
environments = [
  "clx"
]
template_dir = "${XDG_DATA_HOME}/chezmoi/resources/templates/mamba"


[data.instance.packages.config.sdkman]
java_distros = [ ]
