# raspberry pi
[data.instance.packages.debian-rpi.desktop]
apt = [
  "bat",
  "btop",
  "direnv",
  "fd-find",
  "libxcb-render0-dev",
  "libxcb-shape0-dev",
  "libxcb-xfixes0-dev",
  "locales",
  "mosh",
  "ripgrep",
  "shellcheck",
  "zsh"
]
cargo = [
  "--locked zoxide",
  "du-dust",
  "eza",
  "jless"
]
