[data.instance.packages.fedora.desktop]
cargo = [
  "eza",
  "jless"
]
dnf = [
  "bat",
  "btop",
  "du-dust",
  "fd-find",
  "fzf",
  "git",
  "git-delta",
  "libxcb-devel.aarch64",
  "neovim",
  "openssh-server",
  "ripgrep",
  "shellcheck",
  "unzip",
  "zip",
  "zoxide",
  "zsh"
]
