[data.instance.packages.ubuntu.server]
apt = [
  "bat",
  "btop",
  "du-dust",
  "eza",
  "fd-find",
  "fzf",
  "git-delta",
  "neovim",
  "ripgrep",
  "shellcheck",
  "unzip",
  "wtmpdb",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
ppa = [
  "ppa:neovim-ppa/unstable"
]
snap = [ ]
snap-classic = [ ]


[data.instance.packages.ubuntu.desktop]
apt = [
  "bat",
  "btop",
  "du-dust",
  "eza",
  "fd-find",
  "fzf",
  "git-delta",
  "neovim",
  "openssh-server",
  "ripgrep",
  "shellcheck",
  "unzip",
  "wtmpdb",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
ppa = [
  "ppa:neovim-ppa/unstable"
]
snap = [
  "vivaldi"
]
snap-classic = [
  "ghostty" 
]
