[data.instance.packages.darwin.desktop]
brew = [
  "age",
  "ascii",
  "awscli",
  "bat",
  "btop",
  "chezmoi",
  "duckdb",
  "dust",
  "eza",
  "fd",
  "fzf",
  "git-delta",
  "glow",
  "jless",
  "jq",
  "macmon",
  "mas",
  "mise",
  "mosh",
  "neovim",
  "octave",
  "oh-my-posh",
  "qsv",
  "ripgrep",
  "uv",
  "zoxide",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-fast-syntax-highlighting"
]
cask = [
  "blackhole-16ch",
  "font-charis",
  "font-gentium",
  "font-jetbrains-mono-nerd-font",
  "font-meslo-lg-nerd-font",
  "macdown-3000",
  "sage"
]


[data.instance.packages.darwin.ephemeral]
brew = [
  "age",
  "bat",
  "btop",
  "chezmoi",
  "dust",
  "eza",
  "fd",
  "fzf",
  "git-delta",
  "glow",
  "jless",
  "mise",
  "neovim",
  "oh-my-posh",
  "ripgrep",
  "uv",
  "zoxide",
  "zsh-autosuggestions",
  "zsh-completions",
  "zsh-fast-syntax-highlighting"
]
cask = [
  "appcleaner",
  "font-jetbrains-mono-nerd-font",
  "font-meslo-lg-nerd-font",
  "ghostty",
  "iTerm2",
  "macdown-3000",
  "obsidian",
  "visual-studio-code",
  "vivaldi"
]
