[packages.linux.debian.desktop]
apt = [
  "bat",
  "btop",
  "direnv",
  "gdu",
  "fd-find",
  "libxcb-render0-dev",
  "libxcb-shape0-dev",
  "libxcb-xfixes0-dev",
  "ripgrep",
  "shellcheck",
  "unzip",
  "yq",
  "zip",
  "zsh"
]
cargo = [
  "du-dust",
  "eza",
  "jless",
  "zoxide --locked",
]
snap = [ ]
snap-classic = [ ]

[packages.linux.fedora.desktop]
dnf = [
  "bat",
  "btop",
  "direnv",
  "fd-find",
  "fzf",
  "git",
  "gdu",
  "neovim",
  "openssh-server",
  "ripgrep",
  "shellcheck",
  "unzip",
  "yq",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
snap = [ ]
snap-classic = [ ]

[packages.linux.ubuntu.server]
apt = [
  "bat",
  "btop",
  "direnv",
  "du-dust",
  "eza",
  "fd-find",
  "fzf",
  "gdu",
  "neovim",
  "ripgrep",
  "shellcheck",
  "unzip",
  "yq",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
snap = [ ]
snap-classic = [
  "aws-cli" 
]

[packages.linux.ubuntu.desktop]
apt = [
  "bat",
  "btop",
  "direnv",
  "du-dust",
  "gdu",
  "eza",
  "fd-find",
  "fzf",
  "neovim",
  "ripgrep",
  "shellcheck",
  "unzip",
  "yq",
  "zip",
  "zoxide",
  "zsh"
]
cargo = [ ]
snap = [ ]
snap-classic = [
  "aws-cli"
]
