# Use .chezmoidata/instance-options.toml to enable specific-case or ephemeral
# settings without chezmoi management or source control


[instance.options]
# include-zshrc = ["docker-postgis"]

docker-postgis = [
  "# -- postgis-docker",
  "alias depg='docker exec -it postgis /bin/bash'",
  "alias dspg='docker start postgis'",
  "alias dxpg='docker stop postgis'"
]

serial-console = [
  "# -- serial-console",
  "alias s96='screen /dev/ttyUSB0 9600'",
  "alias s115='screen /dev/ttyUSB0 115200'"
]

ubuntu-tegra = [
  "# -- TODO: tegra oddity",
  "unset LESS",
]
